import { Router, type IRouter } from "express";
import healthRouter from "./health";
import coursesRouter from "./courses";
import categoriesRouter from "./categories";
import enrollmentsRouter from "./enrollments";
import progressRouter from "./progress";
import quizzesRouter from "./quizzes";
import commitmentsRouter from "./commitments";
import progressionRouter from "./progression";
import certificatesRouter from "./certificates";
import companiesRouter from "./companies";
import plansRouter from "./plans";
import dashboardRouter from "./dashboard";
import impactRouter from "./impact";
import esgRouter from "./esg";
import learningPathsRouter from "./learningPaths";
import badgesRouter from "./badges";
import leaderboardsRouter from "./leaderboards";
import challengesRouter from "./challenges";
import complianceRouter from "./compliance";
import leadsRouter from "./leads";
import adminRouter from "./admin";
import blogRouter from "./blog";
import recyclingRouter from "./recycling";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/courses", coursesRouter);
router.use("/categories", categoriesRouter);
router.use("/enrollments", enrollmentsRouter);
router.use("/progress", progressRouter);
router.use("/courses", quizzesRouter);
router.use("/courses", commitmentsRouter);
router.use("/progression", progressionRouter);
router.use("/certificates", certificatesRouter);
router.use("/company", companiesRouter);
router.use("/companies", companiesRouter);
router.use("/plans", plansRouter);
router.use("/subscriptions", plansRouter);
router.use("/dashboard", dashboardRouter);
router.use("/impact", impactRouter);
router.use("/esg", esgRouter);
router.use("/learning-paths", learningPathsRouter);
router.use("/badges", badgesRouter);
router.use("/leaderboards", leaderboardsRouter);
router.use("/challenges", challengesRouter);
router.use("/compliance", complianceRouter);
router.use("/leads", leadsRouter);
router.use("/admin", adminRouter);
router.use("/recycling", recyclingRouter);
router.use(blogRouter);

export default router;
